### ISSUE TITLE
Add support for multiple VMs per Vagrantfile

### ISSUE THREAD

**Issue by mperry2** [chornberger-c2c/vagrant-ansible-dynamic-inventory#10]
The script fails when there is more than one VM defined in the Vagrantfile. Since the script is parsing `vagrant global-status --prune`, and it displays the hostname, how about using the VM name, or the VM name and directory name together as the hostname? The network information would need to be extracted somehow too.

``` ruby
Example Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu20" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.network :forwarded_port, guest: 22, host: 2203, id: 'ssh'
  end

  config.vm.define "ubuntu22" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.network :forwarded_port, guest: 22, host: 2204, id: 'ssh'
  end
end
```

Results from running inventory script:

``` text
$ vagrant_inventory.py --list
Traceback (most recent call last):
  File "/Users/mperry/.local/bin/vagrant_inventory.py", line 109, in <module>
    ssh_config = get_ssh_config()
  File "/Users/mperry/.local/bin/vagrant_inventory.py", line 82, in get_ssh_config
    return dict((k, get_a_ssh_config(k)) for k in mapping)
  File "/Users/mperry/.local/bin/vagrant_inventory.py", line 82, in <genexpr>
    return dict((k, get_a_ssh_config(k)) for k in mapping)
  File "/Users/mperry/.local/bin/vagrant_inventory.py", line 98, in get_a_ssh_config
    for identity in host_config['identityfile']:
KeyError: 'identityfile'
```

**Comment by chornberger-c2c** [comment]
@mperry2 

Thanks for raising this issue.
Does the [PR](https://github.com/chornberger-c2c/vagrant-ansible-dynamic-inventory/pull/11)  fix this on your side?

I was able to use it with your example Vagrantfile and two VMs with distinct names.
Also for backwards compatibility the directoy name as Ansible hostname is still supported.

Again, thanks for your feedback.

**Comment by mperry2** [comment]
Yes, it's working properly now. Thanks for the fix!
